### ISSUE TITLE
libX11.so kitaplığını bulamadı.

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [aciklab/Hvl-Lightdm-Greeter#3]
Pisilinux 2.1, Qt5.12.x sistem. 
Build aşamasında kurulu olmasına rağmen libX11.so kitaplığını bulamadı.

**Comment by aliorhun** [comment]
Şimdi incelediğimde kdm olup, lightdm paketi olmadığı için bazı bağımlılıkları eksik bulmakta.
Dolayısıyla şu iki paket bağımlılığını sağlayamadım.
- lightdm
- liblightdm-qt5-3-dev

Diğerleri ise sağlandığını düşünüyorum. Kurduğum bağımlılık paketleri:
- qt5-base-devel
- libxrandr-devel
- libxcursor-devel
- cmake
- qt5-webengine-devel (pisilinux'ta çok fazla bağımlılık gerektiriyor anlamadım, kurumsal selfservis kullanım için kullandığımız için son kullanıcı için gerekmekeyebilir)
- qt5-x11extras-devel

**Comment by onurkepenek** [comment]
f6f2aadcc0ec385834c9e85346d16314a6ffdd67 sorunu çözdü
