### ISSUE TITLE
Düşük Çözünürlükte Ekran Kayması

### ISSUE THREAD

**Issue by duygupotur** [aciklab/Hvl-Lightdm-Greeter#7]
lightdm-hvl-greeter_0.96.2_amd64.deb versiyonunda düşük çözünürlükte (800x600) sağ alt köşedeki panel kayıyor. Bir önceki lightdm-hvl-greeter_0.96.1_amd64.deb versiyonunda düzgün gözüküyordu.

0.96.2 versiyonundaki görüntü aşağıdaki gibidir: 
![lightdm](https://user-images.githubusercontent.com/11041014/71024578-45aa3080-2116-11ea-9a9e-7fa588ec1432.png)

**Comment by onurkepenek** [comment]
d9cca9e da sorun çözülmüştür
